# Generated by Django 4.0.4 on 2022-04-20 10:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('publisher_name', models.CharField(max_length=200)),
                ('num_of_copies', models.IntegerField(default=0)),
                ('price', models.IntegerField(null=True)),
                ('book_image', models.ImageField(default='noimage.png', upload_to='pics/books')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('store', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
