# Generated by Django 4.0.4 on 2022-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='store_id',
            field=models.IntegerField(default=None),
        ),
    ]
